apiVersion : apps/v1
kind: Deployment
metadata:
  name: codedkatespringbootreactapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codedkatespringbootreactapp
  template:
    metadata:
      labels:
        app: codedkatespringbootreactapp 
    spec:
      containers:
        - name: codedkatespringbootreactapp 
          image: springbootreactacr.azurecr.io/codedkatespringbootreactapp
          ports:
          - containerPort: 8080